= Database Table Replicator (DbShadow)
:Author: David Thompson, Matt Conroy
:Email: <dthompsn1@gmail.com> <matt@conroy.cc>
:Revision: 0.0.1 2017-02-08

== Description
Have you ever had the need to copy data from one database to another? How about between to different types of
databases? How about just verifying that your database tables between replicated instances are in sync?

DbShadow is a Java command line application that can help you perform these actions. Using the power of JDBC, it
can read data from one database instance and then using primary keys compare, propogate, and locate differences within
a separate database instance.

== ReleaseNotes
0.0.1 - Base code

== Building
DbShadow uses Scala Build Tool (sbt) in order to build. Clone the repo and type 
....
$ sbt clean compile
....

In order to package the system into a Java binary that's useful for somebody to use:
....
$ sbt clean universal:packageZipTarball
....
This will produce a tarball that can then be installed with a bash script for launching.

== Usage
Help usage is available with the command line.

$ dbshadow -- --help

More documentation to follow.
